# ts => trip-search is a general prefix
services:
  ts-elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.2
    container_name: ts-elasticsearch
    ports:
      - '9200:9200'
      - '9300:9300'
    environment:
      discovery.type: single-node
      ES_JAVA_OPTS: -Xmx512m -Xms512m
      node.name: es01
      xpack.security.enabled: false
      cluster.name: trip-search-cluster  # Corrected cluster name
    networks:
      - ts-elasticnet
    volumes:
      - ./elastic/data:/var/lib/elasticsearch
      - ./elastic/logs:/var/log/elasticsearch

  ts-kibana:
    image: docker.elastic.co/kibana/kibana:8.13.2
    container_name: ts-kibana
    ports:
      - '5601:5601'
      - '9600:9600'
    environment:
      SERVER_NAME: ts-kibana  # Corrected environment variable name
      ELASTICSEARCH_HOSTS: http://ts-elasticsearch:9200  # Corrected Elasticsearch host URL
      ES_JAVA_OPTS: -Xmx512m -Xms512m
    networks:
      - ts-elasticnet
    depends_on:
      - ts-elasticsearch

  ts-springboot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ts-springboot
    restart: always
    ports:
      - "8080:8080"
    networks:
      - ts-elasticnet
    depends_on:
      - ts-elasticsearch
    environment:
      - SPRING_ELASTICSEARCH_URIS=ts-elasticsearch:9200  # Corrected Elasticsearch URL

networks:
  ts-elasticnet:
    driver: bridge

volumes:
  esdata:
    driver: local
